name: blog

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: node version
        run: node -v

      - name: npm version
        run: npm -v

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-email: mhwgodl@163.com
          git-config-name: dongleicode
          folder: build#部署文件夹
          branch: main# 部署到分支（不要选当前分支或开发分支，会覆盖）
          clean: false

